sources:
  # Technology
  - name: "TechCrunch"
    url: "https://feeds.feedburner.com/TechCrunch"
    category: "Technology"
    type: "rss"
  - name: "Wired"
    url: "https://www.wired.com/feed/rss"
    category: "Technology"
    type: "rss"
  - name: "The Verge"
    url: "https://www.theverge.com/rss/index.xml"
    category: "Technology"
    type: "rss"
    
  # Business
  - name: "Financial Times"
    url: "https://www.ft.com/rss/home"
    category: "Business"
    type: "rss"
  - name: "Reuters Business"
    url: "https://feeds.reuters.com/reuters/businessNews"
    category: "Business"
    type: "rss"
  - name: "Bloomberg"
    url: "https://feeds.bloomberg.com/markets/news.rss"
    category: "Business"
    type: "rss"

  # Science & Government Science
  - name: "Science Daily"
    url: "https://www.sciencedaily.com/rss/all.xml"
    category: "Science"
    type: "rss"
  - name: "Nature"
    url: "http://feeds.nature.com/nature/rss/current"
    category: "Science"
    type: "rss"
  - name: "NASA News"
    url: "https://www.nasa.gov/rss/dyn/breaking_news.rss"
    category: "Science"
    type: "rss"
  - name: "USGS News"
    url: "https://www.usgs.gov/news/news-releases/feed"
    category: "Science"
    type: "rss"
  - name: "NOAA News"
    url: "https://www.noaa.gov/feed-items"
    category: "Science"
    type: "rss"
  - name: "EPA News"
    url: "https://www.epa.gov/newsreleases/search/rss"
    category: "Science"
    type: "rss"
  - name: "NSF News"
    url: "https://www.nsf.gov/rss/rss_www_funding.xml"
    category: "Science"
    type: "rss"

  # Health & Government Health
  - name: "WHO News"
    url: "https://www.who.int/rss-feeds/news-english.xml"
    category: "Health"
    type: "rss"
  - name: "NIH News"
    url: "https://www.nih.gov/news-events/news-releases/feed.xml"
    category: "Health"
    type: "rss"
  - name: "CDC News"
    url: "https://tools.cdc.gov/api/v2/resources/media/newsfeeds.rss"
    category: "Health"
    type: "rss"
  - name: "FDA News"
    url: "https://www.fda.gov/about-fda/contact-fda/stay-informed/rss-feeds/press-releases/rss.xml"
    category: "Health"
    type: "rss"

  # Politics & Government Politics
  - name: "Reuters Politics"
    url: "https://feeds.reuters.com/Reuters/PoliticsNews"
    category: "Politics"
    type: "rss"
  - name: "Department of State"
    url: "https://www.state.gov/rss-feed/press-releases/feed/"
    category: "Politics"
    type: "rss"
  - name: "White House Briefings"
    url: "https://www.whitehouse.gov/feed/press-briefings"
    category: "Politics"
    type: "rss"
  - name: "DHS News"
    url: "https://www.dhs.gov/news-releases/rss.xml"
    category: "Politics"
    type: "rss"

  # Sports
  - name: "ESPN"
    url: "https://www.espn.com/espn/rss/news"
    category: "Sports"
    type: "rss"
  - name: "BBC Sport"
    url: "http://feeds.bbci.co.uk/sport/rss.xml"
    category: "Sports"
    type: "rss"
  - name: "Sports Illustrated"
    url: "https://www.si.com/rss/si_main"
    category: "Sports"
    type: "rss"

  # World News
  - name: "Reuters World"
    url: "https://feeds.reuters.com/Reuters/worldNews"
    category: "World"
    type: "rss"
  - name: "BBC World"
    url: "http://feeds.bbci.co.uk/news/world/rss.xml"
    category: "World"
    type: "rss"
  - name: "Department of Defense News"
    url: "https://www.defense.gov/DesktopModules/ArticleCS/RSS.ashx?max=10&ContentType=9&Site=945"
    category: "World"
    type: "rss"

